# TODO: add the path of components
[anchor]
type = "standalone"
component = "Anchor"

[anchor.params]
"1" = "value"

[box]
type = "standalone"
component = "Code"

[box.intrinsic]
boxed = true
highlighted = false
serif = false

[box.params]
"1" = "value"

[core]
type = "standalone"
component = "Code"

[core.intrinsic]
boxed = false
serif = true
highlighted = false

[core.params]
"1" = "value"

[c]
type = "standalone"
component = "Code"

[c.intrinsic]
boxed = true
serif = false
highlighted = true

[c.params]
"1" = "value"
#TODO: cc, cc multi, closed range

[co]
type = "standalone"
component = "Code"

[co.intrinsic]
boxed = false
serif = false
highlighted = true

[co.params]
"1" = "value"

#TODO: cot cob
["collapsed top"]
type = "blockstart"
end = "collapsed end"
component = "Block"

["collapsed top".intrinsic]
#TODO: add intrinsic properties

["collapsed top".params]
"1" = "title"

["collapsed bottom"]
type = "blockend"
